// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Partage_de_fichier.Data;

#nullable disable

namespace Partage_de_fichier.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260309082927_InitialisationBase")]
    partial class InitialisationBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Partage_de_fichier.Models.Fichier", b =>
                {
                    b.Property<int>("IdFichier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFichier"));

                    b.Property<string>("CheminServeur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdProprietaire")
                        .HasColumnType("integer");

                    b.Property<string>("IvAes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdFichier");

                    b.HasIndex("IdProprietaire");

                    b.ToTable("Fichiers");
                });

            modelBuilder.Entity("Partage_de_fichier.Models.PartageAcces", b =>
                {
                    b.Property<int>("IdPartage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPartage"));

                    b.Property<string>("CleAesChiffree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdFichier")
                        .HasColumnType("integer");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer");

                    b.HasKey("IdPartage");

                    b.HasIndex("IdFichier");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("PartagesAcces");
                });

            modelBuilder.Entity("Partage_de_fichier.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("ClePriveeRsaChiffree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClePubliqueRsa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Partage_de_fichier.Models.Fichier", b =>
                {
                    b.HasOne("Partage_de_fichier.Models.Utilisateur", "Proprietaire")
                        .WithMany("FichiersPossedes")
                        .HasForeignKey("IdProprietaire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proprietaire");
                });

            modelBuilder.Entity("Partage_de_fichier.Models.PartageAcces", b =>
                {
                    b.HasOne("Partage_de_fichier.Models.Fichier", "Fichier")
                        .WithMany("AccesPartages")
                        .HasForeignKey("IdFichier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Partage_de_fichier.Models.Utilisateur", "Destinataire")
                        .WithMany("FichiersPartagesAvecMoi")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destinataire");

                    b.Navigation("Fichier");
                });

            modelBuilder.Entity("Partage_de_fichier.Models.Fichier", b =>
                {
                    b.Navigation("AccesPartages");
                });

            modelBuilder.Entity("Partage_de_fichier.Models.Utilisateur", b =>
                {
                    b.Navigation("FichiersPartagesAvecMoi");

                    b.Navigation("FichiersPossedes");
                });
#pragma warning restore 612, 618
        }
    }
}
